blank_issues_enabled: true
contact_links:
  - name: "Question / Discussion"
    url: "https://github.com/IsSabHub/ERP/discussions"
    about: "Utilise Discussions pour les questions générales (si activé)."
